"""Generate native Android files on the cloud builder without replacing Dart code."""

import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
from urllib.parse import urlsplit
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
ANDROID_NS = "http://schemas.android.com/apk/res/android"


def check_config(environ):
    for name in ("API_BASE_URL", "SUPABASE_URL", "SUPABASE_PUBLISHABLE_KEY"):
        if not environ.get(name, "").strip():
            raise ValueError(f"Add {name} to Codemagic's mobile_config variable group.")
    for name in ("API_BASE_URL", "SUPABASE_URL"):
        url = urlsplit(environ[name])
        if url.scheme != "https" or not url.hostname or url.username or url.query or url.fragment:
            raise ValueError(f"{name} must be an HTTPS service URL without credentials or query parameters.")
        if url.path.rstrip("/"):
            raise ValueError(f"{name} must be the service origin, without /api/v1 or another path.")
    key = environ["SUPABASE_PUBLISHABLE_KEY"]
    if key.startswith(("sb_secret_", "gsk_")):
        raise ValueError("Use a Supabase public key for the app, never a server secret.")


def configure_android(mobile):
    manifest = mobile / "android/app/src/main/AndroidManifest.xml"
    ET.register_namespace("android", ANDROID_NS)
    tree = ET.parse(manifest)
    root = tree.getroot()
    name_attribute = f"{{{ANDROID_NS}}}name"
    existing = {node.get(name_attribute) for node in root.findall("uses-permission")}
    for permission in ("android.permission.INTERNET", "android.permission.RECORD_AUDIO"):
        if permission not in existing:
            root.insert(0, ET.Element("uses-permission", {name_attribute: permission}))
    application = root.find("application")
    if application is None:
        raise ValueError("Android manifest has no application element.")
    application.set(f"{{{ANDROID_NS}}}label", "Voice to Text")
    tree.write(manifest, encoding="utf-8", xml_declaration=True)

    gradle = mobile / "android/app/build.gradle.kts"
    if not gradle.is_file():
        raise ValueError("Expected the Kotlin Gradle file generated by the current Flutter SDK.")
    text = gradle.read_text(encoding="utf-8")
    text = re.sub(r"minSdk\s*=\s*flutter\.minSdkVersion", "minSdk = maxOf(23, flutter.minSdkVersion)", text)
    text = re.sub(r"minSdk\s*=\s*(\d+)", lambda match: f"minSdk = {max(23, int(match.group(1)))}", text)
    gradle.write_text(text, encoding="utf-8")


def main():
    if "--check-config" in sys.argv:
        check_config(os.environ)
        print("Public app configuration is present.")
        return
    mobile = ROOT / "mobile"
    android = mobile / "android"
    if not (android / "gradlew").is_file():
        if android.exists():
            raise ValueError("An incomplete Android directory exists; complete it before building.")
        with tempfile.TemporaryDirectory(prefix="voice-android-") as directory:
            scaffold = Path(directory) / "scaffold"
            subprocess.run([
                "flutter", "create", "--platforms=android", "--project-name=voice_to_text",
                "--org=in.startechindia", "--no-pub", str(scaffold),
            ], check=True)
            shutil.copytree(scaffold / "android", android)
    configure_android(mobile)
    print("Android microphone and internet permissions are configured.")


if __name__ == "__main__":
    try:
        main()
    except ValueError as error:
        raise SystemExit(str(error)) from error
